on: [push, pull_request]
name: Test
jobs:
  test:
    name: Ubuntu on node ${{ matrix.node }}
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        os: [ubuntu-18.04]
        node: [13]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - run: yarn global add lerna
    - run: yarn install
    - run: git config --global user.email "patch-package@test.com" && git config --global user.name "patch-package"
    - run: yarn run test
